### ISSUE TITLE
AssetStoreTools がプッシュされたままになっている

### ISSUE THREAD

**Issue by dsuz** [TsuyoshiUsugi/2DFight#3]
アセットストアで DL したアセットを公開状態にしていることが問題だと考えて .gitignore に追加したと想像しますが、追跡から外していないためプッシュされたままになっています。
一旦プッシュされたファイルをリポジトリから消すにはコンソールから git rm コマンドを使って追跡から外す必要があります。やり方がわからない場合は他の人に聞きましょう。

**Comment by TsuyoshiUsugi** [comment]
先程修正しました。ご指摘ありがとうございました。
